{
 "title": "K8S Workload Analysis",
 "tags": [ "perfectscale" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{}, namespace)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\"}, workload)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$workload.*\"}, container)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\"}, workload_type)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "#### PerfectScale Workload Resources Analysis\nBack to [PerfectScale](https://apps.perfectscale.io)\n\n"
   }
  },
  {
   "title": "pods / workload cpu usage (${workload})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{container=~\"$container\",namespace=~\"$namespace\", container!~\"\"}[$__rate_interval])\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n) by (pod, node, container)",
     "legendFormat": "usage: {{pod}} ({{container}})"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_requests{container=~\"$container\", unit=\"core\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n)",
     "legendFormat": "request: ${workload}"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{container=~\"$container\", unit=\"core\", resource=\"cpu\", namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n)",
     "legendFormat": "limit: ${workload}"
    },
    {
     "expr": "max(\n    max_over_time(irate(container_cpu_usage_seconds_total{container=~\"$container\",namespace=~\"$namespace\", container!~\"\"}[$__rate_interval])[$__rate_interval:$__rate_interval])\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n) by (container)",
     "legendFormat": "max-usage: {{container}}"
    }
   ]
  },
  {
   "title": "pods / workload mem usage (${workload})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{container=~\"$container\", namespace=\"$namespace\", container!~\"POD\", container!~\"\", image!~\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n) by (pod, node, container)",
     "legendFormat": "usage: {{container}} [{{pod}}]"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_requests{container=~\"$container\", unit=\"byte\", resource=\"memory\",namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n) ",
     "legendFormat": "request: ${workload}"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{container=~\"$container\", unit=\"byte\", resource=\"memory\",namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n)",
     "legendFormat": "limit: ${workload}"
    },
    {
     "expr": "max\n(\n    max_over_time(container_memory_working_set_bytes{container=~\"$container\", namespace=\"$namespace\", container!~\"POD\", container!~\"\", image!~\"\"}[$__rate_interval])\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n) by (container)",
     "legendFormat": "max-usage: {{container}}"
    }
   ]
  },
  {
   "title": "Network in/out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(container_network_receive_bytes_total{namespace=\"$namespace\",  image!~\"\"}[$__rate_interval])\n    * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n) by (pod, node)",
     "legendFormat": "[in] {{pod}}[{{node}}]"
    },
    {
     "expr": "- sum(\n    rate(container_network_transmit_bytes_total{namespace=\"$namespace\",  image!~\"\"}[$__rate_interval])\n    * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n) by (pod, node)",
     "legendFormat": "[out] {{pod}}[{{node}}]"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  (increase(container_cpu_cfs_throttled_periods_total{container=~\"$container\", container!=\"POD\", container!=\"\", namespace=~\"$namespace\"}[5m])  / \n  increase(container_cpu_cfs_periods_total{container!=\"POD\", container!=\"\", namespace=~\"$namespace\"}[5m]))\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n) by (pod, node, container)",
     "legendFormat": "{{pod}}({{container}}) on {{node}}"
    }
   ]
  },
  {
   "title": "Pods / Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[$__interval])\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n) by (pod, node)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (container, namespace, pod, reason) ( \n\t\t(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$workload.*\", container=~\"$container\"} - kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$workload.*\", container=~\"$container\"} offset $__rate_interval >= 1)\n\t\t* on(namespace,pod, container)\n\t\tgroup_left(reason)\n\t\tmin_over_time(kube_pod_container_status_last_terminated_reason{namespace=~\"$namespace\",pod=~\"$workload.*\", container=~\"$container\"}[$__rate_interval]) == 1\n\t)",
     "legendFormat": "{{reason}} ({{pod}}  {{container}})"
    }
   ]
  },
  {
   "title": "Pods / Phase",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum (\n    kube_pod_status_phase{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"} > 0\n) by (phase, pod)\n",
     "legendFormat": "{{pod}}   |   {{phase}} "
    }
   ]
  },
  {
   "title": "Pods -> Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{container=~\"$container\", namespace=\"$namespace\", container!~\"POD\", container!~\"\", image!~\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=~\"$namespace\", workload=~\"$workload\", workload_type=~\"$type\"}\n) by (pod, node)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}