{
 "title": "K8S Workload Analysis NR",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{}, namespace)"
    }
   },
   { "name": "workload", "query": "coredns.*" },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\", pod=~\"$workload\"}, container)"
    }
   },
   {
    "name": "owner_kind",
    "query": {
     "query": "label_values(kube_pod_owner{namespace=~\"$namespace\", pod=~\"$workload\"}, owner_kind)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "#### PerfectScale Workload Resources Analysis\nBack to [PerfectScale](https://apps.perfectscale.io)\n\n"
   }
  },
  {
   "title": "pods / workload cpu usage (${workload})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{container=~\"$container\",namespace=~\"$namespace\", container!~\"\", pod=~\"$workload\"}[$__rate_interval])\n) by (pod, node, container)",
     "legendFormat": "usage: {{pod}} ({{container}})"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_requests{container=~\"$container\", unit=\"core\", resource=\"cpu\", pod=~\"$workload\"}\n)",
     "legendFormat": "request: ${workload}"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{container=~\"$container\", unit=\"core\", resource=\"cpu\", namespace=\"$namespace\", pod=~\"$workload\"}\n)",
     "legendFormat": "limit: ${workload}"
    },
    {
     "expr": "max(\n    max_over_time(irate(container_cpu_usage_seconds_total{container=~\"$container\",namespace=~\"$namespace\", container!~\"\", pod=~\"$workload\"}[$__rate_interval])[$__rate_interval:$__rate_interval])\n) by (container)",
     "legendFormat": "max-usage: {{container}}"
    }
   ]
  },
  {
   "title": "pods / workload mem usage (${workload})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{container=~\"$container\", namespace=\"$namespace\", container!~\"POD\", container!~\"\", image!~\"\", pod=~\"$workload\"}\n) by (pod, node, container)",
     "legendFormat": "usage: {{container}} [{{pod}}]"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_requests{container=~\"$container\", unit=\"byte\", resource=\"memory\",namespace=\"$namespace\", pod=~\"$workload\"}\n) ",
     "legendFormat": "request: ${workload}"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{container=~\"$container\", unit=\"byte\", resource=\"memory\",namespace=\"$namespace\", pod=~\"$workload\"}\n)",
     "legendFormat": "limit: ${workload}"
    },
    {
     "expr": "max\n(\n    max_over_time(container_memory_working_set_bytes{container=~\"$container\", namespace=\"$namespace\", container!~\"POD\", container!~\"\", image!~\"\",pod=~\"$workload\"}[$__rate_interval])\n) by (container)",
     "legendFormat": "max-usage: {{container}}"
    }
   ]
  },
  {
   "title": "Network in/out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(container_network_receive_bytes_total{namespace=\"$namespace\",  image!~\"\"}[$__rate_interval])\n    * on(namespace,pod)\n    group_left(workload, workload_type) kube_pod_owner{namespace=~\"$namespace\",owner_name=~\"$workload\", owner_kind=~\"$owner_kind\"}\n) by (pod, node)",
     "legendFormat": "[in] {{pod}}[{{node}}]"
    },
    {
     "expr": "- sum(\n    rate(container_network_transmit_bytes_total{namespace=\"$namespace\",  image!~\"\"}[$__rate_interval])\n    * on(namespace,pod)\n    group_left(workload, workload_type) kube_pod_owner{namespace=~\"$namespace\",owner_name=~\"$workload\", owner_kind=~\"$owner_kind\"}\n) by (pod, node)",
     "legendFormat": "[out] {{pod}}[{{node}}]"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  (increase(container_cpu_cfs_throttled_periods_total{container=~\"$container\", container!=\"POD\", container!=\"\", namespace=~\"$namespace\", pod=~\"$workload\"}[5m])  / \n  increase(container_cpu_cfs_periods_total{container!=\"POD\", container!=\"\", namespace=~\"$namespace\", pod=~\"$workload\"}[5m]))\n) by (pod, node, container)",
     "legendFormat": "{{pod}}({{container}}) on {{node}}"
    }
   ]
  },
  {
   "title": "Pods / Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$workload\"}[$__interval]) \n) by (pod, node) > 1",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Terminated Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    kube_pod_container_status_last_terminated_reason{namespace=~\"$namespace\", pod=~\"$workload\"}\n) by (pod, node, reason, container)",
     "legendFormat": "{{reason}}   {{pod}}      [ {{container}} ]"
    }
   ]
  },
  {
   "title": "Pods / Phase",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum (\n    kube_pod_status_phase{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(owner_name, owner_kind) kube_pod_owner{namespace=~\"$namespace\",owner_name=~\"$workload\", owner_kind=~\"$owner_kind\"} > 0\n) by (phase, pod)",
     "legendFormat": "{{pod}}   |   {{phase}} "
    }
   ]
  },
  {
   "title": "Pods -> Nodes no rules",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{container=~\"$container\", namespace=\"$namespace\", container!~\"POD\", container!~\"\", image!~\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) kube_pod_owner{namespace=~\"$namespace\",owner_name=~\"$workload\", owner_kind=~\"$owner_kind\"}\n) by (pod, node)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}