{
 "title": "PerfectScale Prometheus Exporter | Workload Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(ps_recommended_memory_request_bytes,ps_namespace)"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(ps_recommended_memory_request_bytes{ps_namespace=~\"$namespace\"},workload_name)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(ps_recommended_memory_request_bytes{ps_namespace=~\"$namespace\", workload_name=\"$workload\"},ps_container_name)"
    }
   },
   {
    "name": "indicator_level",
    "label": "Indicator level",
    "query": {
     "query": "label_values(ps_workload_indicators{ps_namespace=~\"$namespace\", workload_name=\"$workload\", ps_container_name=\"$container\"},indicator_level)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Request",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(ps_recommended_cpu_request_cores{ps_namespace=~\"${namespace}\", workload_name=~\"${workload}\", ps_container_name=~\"${container}\"}) by (pod, container_name)",
     "legendFormat": "Recommendations Request: Pod: {{workload_name}} Container: {{container_name}}"
    },
    {
     "expr": "sum(ps_current_cpu_request_cores{ps_namespace=~\"${namespace}\", workload_name=~\"${workload}\", ps_container_name=~\"${container}\"}) by (pod, container_name)",
     "legendFormat": "Current Request: Pod: {{workload_name}} Container: {{container_name}}"
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(ps_recommended_cpu_limit_cores{ps_namespace=~\"${namespace}\", workload_name=~\"${workload}\", ps_container_name=~\"${container}\"}) by (pod, container_name)",
     "legendFormat": "Recommendations Limit: Pod: {{workload_name}} Container: {{container_name}}"
    },
    {
     "expr": "sum(ps_current_cpu_limit_cores{ps_namespace=~\"${namespace}\", workload_name=~\"${workload}\", ps_container_name=~\"${container}\"}) by (pod, container_name)",
     "legendFormat": "Current Limit: Pod: {{workload_name}} Container: {{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(ps_recommended_memory_request_bytes{ps_namespace=~\"${namespace}\", workload_name=~\"${workload}\", ps_container_name=~\"${container}\"}) by (pod, container_name)",
     "legendFormat": "Recommendations Request: Pod: {{workload_name}} Container: {{container_name}}"
    },
    {
     "expr": "sum(ps_current_memory_request_bytes{ps_namespace=~\"${namespace}\", workload_name=~\"${workload}\", ps_container_name=~\"${container}\"}) by (pod, container_name)",
     "legendFormat": "Current Request: Pod: {{workload_name}} Container: {{container_name}}"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(ps_recommended_memory_limit_bytes{ps_namespace=~\"${namespace}\", workload_name=~\"${workload}\", ps_container_name=~\"${container}\"}) by (pod, container_name)",
     "legendFormat": "Recommendations Limit: Pod: {{workload_name}} Container: {{container_name}}"
    },
    {
     "expr": "sum(ps_current_memory_limit_bytes{ps_namespace=~\"${namespace}\", workload_name=~\"${workload}\", ps_container_name=~\"${container}\"}) by (pod, container_name)",
     "legendFormat": "Current Limit: Pod: {{workload_name}} Container: {{container_name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ps_replicas_avg{ps_namespace=~\"${namespace}\",workload_name=~\"${workload}\"})",
     "legendFormat": "Max replicas count"
    },
    {
     "expr": "max(ps_replicas_max{ps_namespace=~\"${namespace}\",workload_name=~\"${workload}\"})",
     "legendFormat": "Max replicas count"
    }
   ]
  },
  {
   "title": "Cost & Waste (hourly)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 2, "y": 20 },
   "targets": [
    {
     "expr": "sum(ps_waste_usd{ps_namespace=~\"${namespace}\", workload_name=~\"${workload}\"}) by (workload_name)",
     "legendFormat": "Waste: {{workload_name}}"
    },
    {
     "expr": "sum(ps_cost_usd{ps_namespace=~\"${namespace}\", workload_name=~\"${workload}\"}) by (workload_name)",
     "legendFormat": "Cost: {{workload_name}}"
    }
   ]
  },
  {
   "title": "Indicators",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "sum(ps_workload_indicators{ps_namespace=~\"${namespace}\", workload_name=~\"${workload}\", ps_container_name=~\"${container}\", indicator_name!=\"\", indicator_level=~\"${indicator_level}\" }) by (indicator_name, indicator_level, container_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}